CREATE TABLE organisation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   version INTEGER,
   creator_id BIGINT,
   name VARCHAR(255),
   code VARCHAR(255),
   description VARCHAR(255),
   picture VARCHAR(255),
   longitude DOUBLE PRECISION,
   latitude DOUBLE PRECISION,
   CONSTRAINT pk_organisation PRIMARY KEY (id)
);

CREATE TABLE organisation_projects (
  organisation_id BIGINT NOT NULL,
   project_id BIGINT NOT NULL
);

CREATE TABLE project_users (
  project_id BIGINT NOT NULL,
   user_id BIGINT NOT NULL
);

CREATE TABLE organisation_users (
  organisation_id BIGINT NOT NULL,
   user_id BIGINT NOT NULL
);

ALTER TABLE organisation ADD CONSTRAINT FK_ORGANISATION_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES users (id);

ALTER TABLE organisation_projects ADD CONSTRAINT fk_orgpro_on_organisation FOREIGN KEY (organisation_id) REFERENCES organisation (id);

ALTER TABLE organisation_projects ADD CONSTRAINT fk_orgpro_on_project FOREIGN KEY (project_id) REFERENCES project (id);

ALTER TABLE project_users ADD CONSTRAINT fk_prouse_on_project FOREIGN KEY (project_id) REFERENCES project (id);

ALTER TABLE project_users ADD CONSTRAINT fk_prouse_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE organisation_users ADD CONSTRAINT fk_orguse_on_org FOREIGN KEY (organisation_id) REFERENCES organisation (id);

ALTER TABLE organisation_users ADD CONSTRAINT fk_orguse_on_user FOREIGN KEY (user_id) REFERENCES users (id);