CREATE TABLE IF NOT EXISTS project_member_relation (
  project_role_id BIGINT,
   project_id BIGINT NOT NULL,
   member_id BIGINT NOT NULL,
   CONSTRAINT pk_projectmemberrelation PRIMARY KEY (project_id, member_id)
);

CREATE TABLE IF NOT EXISTS project_role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   version INTEGER,
   name VARCHAR(255),
   CONSTRAINT pk_projectrole PRIMARY KEY (id)
);

ALTER TABLE organisation ADD corporate_name VARCHAR(255);

ALTER TABLE organisation ADD country VARCHAR(255);

ALTER TABLE organisation ADD legal_structure VARCHAR(255);

ALTER TABLE organisation ADD postal_code VARCHAR(255);

ALTER TABLE organisation ADD region VARCHAR(255);

ALTER TABLE organisation ADD sector VARCHAR(255);

ALTER TABLE organisation ADD town VARCHAR(255);

ALTER TABLE project_member_relation ADD CONSTRAINT FK_PROJECTMEMBERRELATION_ON_MEMBER FOREIGN KEY (member_id) REFERENCES users (id);

ALTER TABLE project_member_relation ADD CONSTRAINT FK_PROJECTMEMBERRELATION_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);

ALTER TABLE project_member_relation ADD CONSTRAINT FK_PROJECTMEMBERRELATION_ON_PROJECT_ROLE FOREIGN KEY (project_role_id) REFERENCES project_role (id);

ALTER TABLE project_users DROP CONSTRAINT fk_prouse_on_project;

ALTER TABLE project_users DROP CONSTRAINT fk_prouse_on_user;

DROP TABLE project_users CASCADE;