CREATE TABLE IF NOT EXISTS org_member_relation
(
    org_role_id BIGINT,
    org_id      BIGINT NOT NULL,
    member_id   BIGINT NOT NULL,
    CONSTRAINT pk_orgmemberrelation PRIMARY KEY (org_id, member_id)
);

CREATE TABLE IF NOT EXISTS org_role
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version     INTEGER,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_orgrole PRIMARY KEY (id)
);

ALTER TABLE organisation
    ADD join_requests JSONB;

ALTER TABLE org_member_relation
    ADD CONSTRAINT FK_ORGMEMBERRELATION_ON_MEMBER FOREIGN KEY (member_id) REFERENCES users (id);

ALTER TABLE org_member_relation
    ADD CONSTRAINT FK_ORGMEMBERRELATION_ON_ORG FOREIGN KEY (org_id) REFERENCES organisation (id);

ALTER TABLE org_member_relation
    ADD CONSTRAINT FK_ORGMEMBERRELATION_ON_ORG_ROLE FOREIGN KEY (org_role_id) REFERENCES org_role (id);

ALTER TABLE organisation_users
DROP
CONSTRAINT fk_orguse_on_org;

ALTER TABLE organisation_users
DROP
CONSTRAINT fk_orguse_on_user;

DROP TABLE organisation_users CASCADE;