CREATE TABLE IF NOT EXISTS projects_project_node_type (
   project_id BIGINT NOT NULL,
   type_id BIGINT NOT NULL,
   CONSTRAINT pk_projs_pr_node_t PRIMARY KEY (project_id, type_id),
   CONSTRAINT pk_pr_pr_n_pr_id FOREIGN KEY (project_id) REFERENCES project(id),
   CONSTRAINT pk_pr_pr_n_ty_id FOREIGN KEY (type_id) REFERENCES project_node_type(id)
);
CREATE TABLE IF NOT EXISTS project_node_status (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   version INTEGER,
   creator_id BIGINT NULL,
   label VARCHAR(255),
   icon_name VARCHAR(255) NULL,
   CONSTRAINT pk_projnodestat PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS projects_project_node_status (
      project_id BIGINT NOT NULL,
      status_id BIGINT NOT NULL,
      CONSTRAINT pk_projs_pr_status_t PRIMARY KEY (project_id, status_id),
      CONSTRAINT pk_pr_pr_nsta_pr_id FOREIGN KEY (project_id) REFERENCES project(id),
      CONSTRAINT pk_pr_pr_n_sta_id FOREIGN KEY (status_id) REFERENCES project_node_status(id)
);

INSERT INTO project_node_status (version, label, icon_name) VALUES
(0, 'todo', 'todo'),
(0, 'in-progress', 'in-progress'),
(0, 'in-review', 'in-review'),
(0, 'done', 'done'),
(0, 'planned', 'planned'),
(0, 'not-planned', 'not-planned'),
(0, 'deployed', 'deployed'),
(0, 'delivered', 'delivered');
