CREATE TABLE project_node (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   version INTEGER,
   creator_id BIGINT,
   name VARCHAR(255),
   code VARCHAR(255),
   longitude DOUBLE PRECISION,
   latitude DOUBLE PRECISION,
   node_type_id BIGINT,
   CONSTRAINT pk_projectnode PRIMARY KEY (id)
);

CREATE TABLE project_node_relation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   version INTEGER,
   start BIGINT,
   "end" BIGINT,
   label VARCHAR(255),
   CONSTRAINT pk_projectnoderelation PRIMARY KEY (id)
);

ALTER TABLE project ADD project_node BIGINT NULL;

ALTER TABLE project_node_relation ADD CONSTRAINT FK_PROJECTNODERELATION_ON_END FOREIGN KEY ("end") REFERENCES project_node (id);

ALTER TABLE project_node_relation ADD CONSTRAINT FK_PROJECTNODERELATION_ON_START FOREIGN KEY (start) REFERENCES project_node (id);

ALTER TABLE project_node ADD CONSTRAINT FK_PROJECTNODE_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES users (id);

ALTER TABLE project_node ADD CONSTRAINT FK_PROJECTNODE_ON_NODE_TYPE FOREIGN KEY (node_type_id) REFERENCES project_node_type (id);

ALTER TABLE project ADD CONSTRAINT FK_PROJECT_ON_PROJECT_NODE FOREIGN KEY (project_node) REFERENCES project_node (id);

ALTER TABLE project DROP COLUMN project_nodes;