export POSTGRESQL_ADDON_DB=bwxeqs55pjobjd2pdarh

export POSTGRESQL_ADDON_HOST=bwxeqs55pjobjd2pdarh-postgresql.services.clever-cloud.com

export POSTGRESQL_ADDON_PASSWORD=cBOCQ7ZmGvMo4wD9epA3

export POSTGRESQL_ADDON_PORT=5432

export POSTGRESQL_ADDON_URI=postgresql://uev9lfhdyi8ashipeewm:cBOCQ7ZmGvMo4wD9epA3@bwxeqs55pjobjd2pdarh-postgresql.services.clever-cloud.com:5432/bwxeqs55pjobjd2pdarh

export POSTGRESQL_ADDON_USER=uev9lfhdyi8ashipeewm

export POSTGRESQL_ADDON_VERSION=11

